### ISSUE TITLE
Attachments do not seem to work

### ISSUE THREAD

**Issue by delsehi** [4teamwork/weasyprint-docker#6]
In the README it says that attachments should start with **file.** as a prefix. In the code in *server.py* however there's **"attachment."** and **"asset."**. Maybe that should be updated? 

I'm not good at Python but it also seems that files starting with "asset." will only be read but not added to the attachments array. 

And I cannot get attachments to work at all. I'm trying to add *.png* images but they do not show in the pdf. 

I've tried doing it from Node.js with FormData and curl. 

This does not work. I've got ananas.png and test.html in the same directory. 

`curl -F 'html=@test.html' -F 'attachment.ananas.png=@ananas.png'  <WEASY PRINT URL> -o test.pdf`

And I've referenced the image as `<img src="ananas.png">` and `<img src="attachment.ananas.png">` but it's just empty. HTML and CSS works however.

**Comment by buchi** [comment]
Yes. The README was wrong and because URL fetching was disabled, it didn't work with asset./attachment. prefixes as well.

This is now fixed in the latest image (58.1)
